CREATE MASTER KEY;
GO
CREATE DATABASE SCOPED CREDENTIAL [AzureStorageCredential]
    WITH IDENTITY = N'user';
GO
CREATE DATABASE SCOPED CREDENTIAL [dsc_ccd]
    WITH IDENTITY = N'user';
GO
CREATE DATABASE SCOPED CREDENTIAL [persistent]
    WITH IDENTITY = N'mipersistentsbox';


