# .NET Desktop
# Build and run tests for .NET Desktop or Windows classic desktop solutions.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/windows/dot-net

trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  sqlDwPath: 'synapse'
  azure.subscription.endpoint: 'DTS-SHAREDSERVICES-TEST'
  sqlsrvrName: ''

stages:
- stage: 'validate'
  displayName: 'Validate project'
  # condition: and(always(), eq(variables['Build.Reason'], 'PullRequest'))
  jobs:
  - job: 'validate_sql_packages'
    displayName: 'Validate sql project'
    pool:
      vmImage: 'windows-latest'
    steps:
    - task: NuGetToolInstaller@1

    - task: NuGetCommand@2
      inputs:
        restoreSolution: '$(solution)'

    - task: VSBuild@1
      inputs:
        solution: '$(solution)'
        platform: '$(buildPlatform)'
        configuration: '$(buildConfiguration)'

    - task: VSTest@2
      inputs:
        platform: '$(buildPlatform)'
        configuration: '$(buildConfiguration)'

    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(sqlDwPath)/bin/$(buildConfiguration)/synapse.dacpac'
        ArtifactName: 'sql_dw_dacpac'
      displayName: 'Publish SQL DACPAC'  
  
  - deployment: deploy_azuresqldw
    displayName: 'Deploy to AzureSQLDW'
    pool:
      vmImage: 'windows-latest'
    variables:
      sqlProjName: ddo_azuresqldw_dw
    environment: $(environment)
    strategy:
      runOnce:
        deploy:
          steps:
          - task: DownloadPipelineArtifact@2
            inputs:
              # artifact: 'sql_dw_dacpac'
              path: $(Build.SourcesDirectory)\bin
          # https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/sql-azure-dacpac-deployment?view=azure-devops
          - task: SqlAzureDacpacDeployment@1
            inputs:
              azureSubscription: $(azure.subscription.endpoint)
              AuthenticationType: 'server'
              ServerName: $(sqlsrvrName).database.windows.net
              DatabaseName: $(sqlDwDatabaseName)
              SqlUsername: '$(sqlsrvrUsername)'
              SqlPassword: '$(sqlsrvrPassword)'
              deployType: 'DacpacTask'
              DacpacFile: '$(Build.SourcesDirectory)\bin\sql_dw_dacpac\synapse.dacpac' #'$(Pipeline.Workspace)/s/synapse/bin/Release/synapse.dacpac' 
              AdditionalArguments: '/Variables:PipelinePassword=$(pipelinePassword)'
            displayName: 'Azure SQL Dacpac'

    # - task: SqlAzureDacpacDeployment@1
    #   inputs:
    #     AuthenticationType: 'server'
    #     ServerName: 'mi-datawarehouse-server-sbox'
    #     DatabaseName: 'datawarehouse-db-sbox'
    #     SqlUsername: 'login_user'
    #     SqlPassword: 'login_password'
    #     deployType: 'DacpacTask'
    #     DeploymentAction: 'Script'
    #     DacpacFile: 'temporal.dacpac'
    #     IpDetectionMethod: 'AutoDetect'
 