parameters:
- name: azureSubscriptionEndpoint
  type: string
  default: ''
- name: keyVaultName
  type: string
  default: ''
- name: azureSecreKeys
  type: string
  default: '*'
  
steps:
  - task: AzureKeyVault@1
    displayName: 'Get Secrets From Keyvault'
    inputs:
      azureSubscription: ${{ parameters.azureSubscriptionEndpoint }}
      keyVaultName: ${{ parameters.keyVaultName }}
      secretsFilter: ${{ parameters.azureSecreKeys }}