CREATE EXTERNAL FILE FORMAT [TextFileFormat]
    WITH (
    FORMAT_TYPE = DELIMITEDTEXT,
    FORMAT_OPTIONS (FIELD_TERMINATOR = N'|', DATE_FORMAT = N'yyyy-MM-dd HH:mm:ss.fff', FIRST_ROW = 1, ENCODING = N'UTF8')
    );

