parameters:
- name: environment
  type: string
- name: artifactName
  type: string
- name: projectName
  type: string
- name: databaseName
  type: string
- name: databaseServerName
  type: string
- name: subscriptionEndpoint
  type: string
- name: keyvaultName
  type: string
- name: readerGroup
  type: string
  default: 'DTS Readers Data Platform Nonprod'

jobs:
  - deployment: deploy_azuresqldw
    displayName: 'Deploy to AzureSQLDW'
    # condition: eq(variables['build.sourceBranch'], 'refs/heads/master')  #disable job for testing
    pool: hmcts-ss-sandbox

    variables:
      sqlProjName: ${{ parameters.projectName }}
      sqlDwDatabaseName: ${{ parameters.databaseName }}
    environment: ${{ parameters.environment }}
    strategy:
      runOnce:
        deploy:
          steps:
          - checkout: self
            path: 'self'
          - task: Bash@3
            displayName: 'List directory'
            inputs:
              targetType: inline
              script: 'ls -lR'
          - template: ../tasks/vault-secrets.yaml
            parameters: 
              azureSubscriptionEndpoint: $(azure.subscription.endpoint)
              keyVaultName: ${{ parameters.keyvaultName }}
              azureSecreKeys: '*'
          - task: DownloadBuildArtifacts@0
            inputs:
              downloadPath: $(System.ArtifactsDirectory)
              artifactName: ${{ parameters.artifactName }} #'sql_dw_dacpac'
          - task: Bash@3
            displayName: 'Azure SQL Dacpac backup'
            inputs:
              targetType: filePath
              filePath: '$(Pipeline.Workspace)/self/_scripts/deploySqlPackage.sh'
            env:
              ServerName: ${{parameters.databaseServerName }}.database.windows.net
              DatabaseName: ${{ parameters.databaseName }}
              SqlUsername: '$(mi-datawarehouse-server-admin-user)'
              SqlPassword: '$(mi-datawarehouse-server-admin-password)'
              DeploymentAction: 'Extract'
              TargetFile: 'backup.dacpac'
          - task: Bash@3
            displayName: 'Deploy Azure SQL Dacpac'
            inputs:
              targetType: filePath
              filePath: '$(Pipeline.Workspace)/self/_scripts/deploySqlPackage.sh'
            env:
              TargetServerName: ${{parameters.databaseServerName }}.database.windows.net
              TargetDatabaseName: ${{ parameters.databaseName }}
              TargetUser: '$(mi-datawarehouse-server-admin-user)'
              TargetPassword: '$(mi-datawarehouse-server-admin-password)'
              DeploymentAction: 'Publish'
              DacpacFile: '$(System.ArtifactsDirectory)/sql_dw_dacpac/$(sqlProjName).dacpac' 
              AdditionalArguments: '/Variables:SqlDwDatabaseName=${{ parameters.databaseName }} /Variables:PipelinePassword=$(pipelinePassword) /Variables:"readerGroup=${{ parameters.readerGroup }}"'
