parameters:
- name: environment
  type: string
- name: subscriptionEndpoint
  type: string
- name: adfName
  type: string
- name: resourceGroup
  type: string
- name: adfOverrideParameters
  type: string
jobs:
- deployment: deploy_adf
  dependsOn: deploy_azuresqldw
  displayName: 'Deploy to Azure Data Factory'
  pool: hmcts-ss-sandbox

  variables:
    packageWheelName: 'none'
  environment: ${{ parameters.environment }}
  strategy:
    runOnce:
      deploy:
        steps:
        - checkout: self
          path: 'self'
        - checkout: mi_synapse_integration
          path: 'adf_publish'

        - task: CmdLine@2
          displayName: 'Prepare Az environment'
          inputs:
            script: 'pwsh --command Install-Module -Name Az.Accounts -RequiredVersion 2.1.2 -AllowClobber -Force'
        - task: AzurePowerShell@4
          inputs:
            azureSubscription: ${{ parameters.subscriptionEndpoint }}
            ScriptPath: '$(Pipeline.Workspace)/self/_scripts/deploymentadf.ps1'
            ScriptArguments: '-armTemplate "$(Pipeline.Workspace)/adf_publish/ARMTemplateForFactory.json" -ResourceGroupName "${{ parameters.resourceGroup }}" -DataFactoryName "${{ parameters.adfName }}" -predeployment $true'
            azurePowerShellVersion: LatestVersion
          displayName: 'Azure PowerShell script: Stop ADF triggers'
        - task: AzureResourceGroupDeployment@2
          displayName: 'Azure Deployment:Create Or Update Resource Group action on ${{ parameters.resourceGroup }}'
          inputs:
            azureSubscription: ${{ parameters.subscriptionEndpoint }}
            resourceGroupName: ${{ parameters.resourceGroup }}
            location: '$(azureLocation)'
            csmFile: '$(Pipeline.Workspace)/adf_publish/ARMTemplateForFactory.json'
            csmParametersFile: '$(Pipeline.Workspace)/adf_publish/ARMTemplateParametersForFactory.json'
            overrideParameters: -factoryName ${{ parameters.adfName }} ${{ parameters.adfOverrideParameters }} 
        - task: AzurePowerShell@4
          displayName: 'Azure PowerShell script: Start ADF triggers'
          inputs:
            azureSubscription: ${{ parameters.subscriptionEndpoint }}
            ScriptPath: '$(Pipeline.Workspace)/self/_scripts/deploymentadf.ps1'
            ScriptArguments: '-armTemplate "$(Pipeline.Workspace)/adf_publish/ARMTemplateForFactory.json" -ResourceGroupName "${{ parameters.resourceGroup }}" -DataFactoryName "${{ parameters.adfName }}" -predeployment $false'
            azurePowerShellVersion: LatestVersion