parameters:
- name: environment
  type: string
- name: subscriptionEndpoint
  type: string

jobs:
- deployment: deploy_adf
  # dependsOn: deploy_azuresqldw
  displayName: 'Deploy to Azure Data Factory'
  pool: hmcts-ss-sandbox

  variables:
    packageWheelName: 'none'
  environment: ${{ parameters.environment }}
  strategy:
    runOnce:
      deploy:
        steps:
        - checkout: self
        - checkout: mi_synapse_integration
          path: 'adf_publish'

          # https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/azure-resource-group-deployment
        - task: CmdLine@2
          inputs:
            script: 'dir $(Pipeline.Workspace)'

          # https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/azure-powershell
        - task: CmdLine@2
          inputs:
            script: 'pwsh -File $(Pipeline.Workspace)/_scripts/deploymentadf.ps1 -armTemplate "$(Pipeline.Workspace)/adf_publish/$(devAdfName)/ARMTemplateForFactory.json" -ResourceGroupName "$(rgName)" -DataFactoryName "$(adfName)" -predeployment $true'
          displayName: 'Azure PowerShell script: Stop ADF triggers'


        - task: AzureResourceGroupDeployment@2
          displayName: 'Azure Deployment:Create Or Update Resource Group action on $(rgName)'
          inputs:
            azureSubscription: ${{ parameters.subscriptionEndpoint }}
            resourceGroupName: '$(rgName)'
            location: '$(azureLocation)'
            csmFile: '$(Pipeline.Workspace)/adf_publish/$(devAdfName)/ARMTemplateForFactory.json'
            csmParametersFile: '$(Pipeline.Workspace)/adf_publish/$(devAdfName)/ARMTemplateParametersForFactory.json'
            overrideParameters: -factoryName "$(adfName)" -AzureBlobStorage1_properties_typeProperties_serviceEndpoint "https://$(persistentStorage).blob.core.windows.net"

        # https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/azure-powershell
        - task: CmdLine@2
          displayName: 'Azure PowerShell script: Start ADF triggers'
          inputs:
            script: 'pwsh -File $(Pipeline.Workspace)/_scripts/deploymentadf.ps1 -armTemplate "$(Pipeline.Workspace)/adf_publish/$(devAdfName)/ARMTemplateForFactory.json" -ResourceGroupName "$(rgName)" -DataFactoryName "$(adfName)" -predeployment $false'

