parameters:
- name: databaseName
  type: string
  default: mi-datawarehouse-db-$(environment)
- name: databaseServerName
  type: string
  default: mi-datawarehouse-server-$(environment)
- name: subscriptionEndpoint
  type: string
- name: adfName
  type: string
- name: resourceGroup
  type: string
  default: mi-$(environment)-rg
- name: keyvaultName
  type: string
  default: mi-vault-$(environment)
- name: ssKeyvaultName
  type: string
  default: ss-vault-$(environment)
- name: pipelineName
  type: string

jobs:
- job: run_integration_tests
  displayName: 'Run integration tests'
  dependsOn: deploy_adf
  pool: hmcts-ss-sandbox

  variables:
    pythonWorkingDir: './'
    pythonVersion: 3.6
  steps:
  - script: |
      curl https://packages.microsoft.com/keys/microsoft.asc | apt-key add -
      bash -c "curl https://packages.microsoft.com/config/debian/10/prod.list > /etc/apt/sources.list.d/mssql-release.list"
      apt-get update
      ACCEPT_EULA=Y apt-get -y install msodbcsql17 unixodbc-dev python3-dev python3-pip
    displayName: 'Install msodbc'
  - template: ../tasks/vault-secrets.yaml
    parameters: 
      azureSubscriptionEndpoint: $(azure.subscription.endpoint)
      keyVaultName: ${{ parameters.keyvaultName }}
      azureSecreKeys: '*'
  - template: ../tasks/vault-secrets.yaml
    parameters:
      azureSubscriptionEndpoint: $(azure.subscription.endpoint)
      keyVaultName: ${{ parameters.ssKeyvaultName }}
      azureSecreKeys: '*'
  # - task: UsePythonVersion@0
  #   inputs:
  #     versionSpec: '$(pythonVersion)'
  #     addToPath: true
  #   displayName: 'Use Python Version: $(pythonVersion)'

  - script: |
      bash --version
      alias python=python3
      python --version
      curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
      python3 get-pip.py
      pip install -r requirements.txt
    workingDirectory: $(pythonWorkingDir)
    displayName: 'Install requirements'
  - task: AzurePowerShell@4
    displayName: 'PipelineExecutor'
    inputs:
      azureSubscription: ${{ parameters.subscriptionEndpoint }}
      ScriptPath: '$(Pipeline.Workspace)/self/_scripts/executeDataFactoryPipeline.ps1'
      ScriptArguments: '-PipelineName ${{parameters.pipelineName }} -ResourceGroupName ${{parameters.resourceGroup }} -DataFactoryName ${{ parameters.adfName }}'
      azurePowerShellVersion: LatestVersion
  - script: make test
    workingDirectory: $(pythonWorkingDir)
    env:
      SQL_SERVER_NAME: ${{parameters.databaseServerName }}
      SQL_DATABASE_NAME: ${{ parameters.databaseName }}
      SQL_SERVER_USERNAME: '$(mi-datawarehouse-server-admin-user)'
      SQL_SERVER_PASSWORD: '$(mi-datawarehouse-server-admin-password)'  
      AZ_SERVICE_PRINCIPAL_ID: $(AZ_SERVICE_PRINCIPAL_ID)
      AZ_SERVICE_PRINCIPAL_SECRET: $(AZ_SERVICE_PRINCIPAL_SECRET)
      AZ_SERVICE_PRINCIPAL_TENANT_ID: $(AZ_SERVICE_PRINCIPAL_TENANT_ID)
      AZ_SUBSCRIPTION_ID: ${{ parameters.subscriptionEndpoint }}
      AZ_RESOURCE_GROUP_NAME: ${{parameters.resourceGroup }}
      AZ_DATAFACTORY_NAME: ${{ parameters.adfName }}
      PIPELINE_EXECUTION_SATTUS: $(PipelineExecutor.pipelineExecutionStatus)
    displayName: 'Run integration tests'

  - script: make coverage
    workingDirectory: $(pythonWorkingDir)
    env:
      SQL_SERVER_NAME: ${{parameters.databaseServerName }}
      SQL_DATABASE_NAME: ${{ parameters.databaseName }}
      SQL_SERVER_USERNAME: '$(mi-datawarehouse-server-admin-user)'
      SQL_SERVER_PASSWORD: '$(mi-datawarehouse-server-admin-password)'  
      AZ_SERVICE_PRINCIPAL_ID: $(AZ_SERVICE_PRINCIPAL_ID)
      AZ_SERVICE_PRINCIPAL_SECRET: $(AZ_SERVICE_PRINCIPAL_SECRET)
      AZ_SERVICE_PRINCIPAL_TENANT_ID: $(AZ_SERVICE_PRINCIPAL_TENANT_ID)
      AZ_SUBSCRIPTION_ID: ${{ parameters.subscriptionEndpoint }}
      AZ_RESOURCE_GROUP_NAME: ${{parameters.resourceGroup }}
      AZ_DATAFACTORY_NAME: ${{ parameters.adfName }}
    displayName: 'Run test coverage'

  - task: PublishTestResults@2
    condition: succeededOrFailed()
    inputs:
      testResultsFormat: 'JUnit'
      testResultsFiles: '**/reports/test/*.xml'

  - task: PublishPipelineArtifact@1
    condition: succeededOrFailed()
    inputs:
      path: '$(System.DefaultWorkingDirectory)/reports/test/'
      artifact: 'test'
      displayName: 'Publish test report'