CREATE TABLE [MDM].[DIM_EVENT_TYPE] (
    [EVENT_TYPE_KEY]            DECIMAL (10, 6) NOT NULL,
    [SRC_SYSTEM_CODE]           VARCHAR (4)     NOT NULL,
    [EVENT_NAME]                VARCHAR (255)   NOT NULL,
    [SRC_EVENT_TYPE]            VARCHAR (100)   NOT NULL,
    [GENERIC_EVENT_NAME]        VARCHAR (30)    NULL,
    [GENERIC_EVENT_GROUP]       VARCHAR (30)    NULL,
    [MI_EVENT_GROUP]            VARCHAR (100)   NULL,
    [SRC_SYSTEM_CASE_TYPE_NAME] VARCHAR (50)    NULL
)
WITH (CLUSTERED COLUMNSTORE INDEX, DISTRIBUTION = ROUND_ROBIN);

