CREATE TABLE [MDM].[DIM_CASE_TYPE] (
    [CASE_TYPE_CODE]       DECIMAL (10, 6) NOT NULL,
    [SOURCE_SYSTEM_CODE]   DECIMAL (10, 6) NOT NULL,
    [CASE_TYPE_DESCRIPTOR] VARCHAR (100)   NULL,
    [MAJOR_CASE_TYPE]      VARCHAR (50)    NULL,
    [MINOR_CASE_TYPE]      VARCHAR (50)    NULL,
    [CASE_TYPE_KEY]        DECIMAL (10, 6) NOT NULL,
    [GENERIC_CASE_TYPE]    VARCHAR (100)   NULL,
    [HIGH_COURT]           CHAR (1)        DEFAULT ('N') NULL,
    [JURISDICTION_KEY]     DECIMAL (10, 6) NULL
)
WITH (CLUSTERED COLUMNSTORE INDEX, DISTRIBUTION = ROUND_ROBIN);


GO
CREATE NONCLUSTERED INDEX [DIM_CASE_TYPE_IDX1]
    ON [MDM].[DIM_CASE_TYPE]([CASE_TYPE_KEY] ASC);

