CREATE TABLE [MDM].[DIM_CHANNEL_METHOD_TYPE] (
    [CHANNEL_METHOD_TYPE_KEY]  DECIMAL (10, 6) NULL,
    [CHANNEL_METHOD_TYPE_NAME] VARCHAR (100)   NULL
)
WITH (CLUSTERED COLUMNSTORE INDEX, DISTRIBUTION = ROUND_ROBIN);


GO
CREATE NONCLUSTERED INDEX [DIM_CHANNEL_METHOD_TYPE_IDX1]
    ON [MDM].[DIM_CHANNEL_METHOD_TYPE]([CHANNEL_METHOD_TYPE_KEY] ASC);

