CREATE TABLE [MDM].[DIM_JURISDICTION] (
    [JURISDICTION_KEY]           DECIMAL (10, 6) NULL,
    [JURISDICTION_NAME]          VARCHAR (100)   NULL,
    [CAFE_JURIS_ID]              FLOAT (53)      NULL,
    [CAFE_JURIS_NAME]            VARCHAR (100)   NULL,
    [JURISDCTN_CATGRY_NAME]      VARCHAR (20)    NULL,
    [CSPC_JURISDCTN_CATGRY_NAME] VARCHAR (20)    NULL
)
WITH (CLUSTERED COLUMNSTORE INDEX, DISTRIBUTION = ROUND_ROBIN);


GO
CREATE NONCLUSTERED INDEX [DIM_JURISDICTION_IDX1]
    ON [MDM].[DIM_JURISDICTION]([JURISDICTION_KEY] ASC);

