CREATE TABLE [MDM].[MDM_ATTR_TYPE] (
    [ATTR_KEY]                     DECIMAL (10, 6) NOT NULL,
    [ATTR_LOGICAL_NAME]            VARCHAR (255)   NULL,
    [ATTR_ORIGINAL_NAME]           VARCHAR (50)    NULL,
    [ATTR_PHYSICAL_NAME]           VARCHAR (30)    NULL,
    [ATTR_DOMAIN_TYPE_NAME]        VARCHAR (50)    NULL,
    [ATTR_DATA_TYPE_NAME]          VARCHAR (50)    NULL,
    [BIS_FIRST_CREATED_DATETIME]   DATETIME        NULL,
    [BIS_LAST_CREATED_DATETIME]    DATETIME        NULL,
    [BIS_MODIFIED_BY_PROCESS_NAME] VARCHAR (50)    NULL,
    [BIS_INSERTED_BY_PROCESS_NAME] VARCHAR (50)    NULL,
    [SOURCE_SYSTEM_TYPE_CODE]      VARCHAR (50)    NULL,
    [JURISDICTION_CODE]            VARCHAR (50)    NULL
)
WITH (CLUSTERED COLUMNSTORE INDEX, DISTRIBUTION = ROUND_ROBIN);

