CREATE TABLE [PROBATE].[STG_CCD_PROBATESRCH] (
    [MD_INSERT_TIME]         DATETIMEOFFSET (6) NULL,
    [CASE_METADATA_EVENT_ID] DECIMAL (38)       NULL,
    [CE_APP_TYPE]            VARCHAR (255)      NULL,
    [CE_REG_LOCATION]        VARCHAR (255)      NULL,
    [CE_EXPIRY_DATE]         DATETIME           NULL,
    [LOADED_DATETIME]        DATETIME           NULL,
    [CE_LEG_RECORD_ID]       DECIMAL (38)       NULL,
    [CE_APP_SUB_DATE]        DATETIME           NULL
)
WITH (CLUSTERED COLUMNSTORE INDEX, DISTRIBUTION = ROUND_ROBIN);

