CREATE TABLE [PROBATE].[STG_CCD_METADATA] (
    [MD_INSERT_TIME]       DATETIMEOFFSET (6) NULL,
    [CE_ID]                DECIMAL (38)       NULL,
    [CE_CASE_DATA_ID]      DECIMAL (38)       NULL,
    [CE_CREATED_DATE]      DATETIME           NULL,
    [CE_CASE_TYPE_ID]      VARCHAR (255)      NULL,
    [CE_CASE_TYPE_VERSION] FLOAT (53)         NULL,
    [CE_EVENT_ID]          VARCHAR (100)      NULL,
    [CE_EVENT_NAME]        VARCHAR (255)      NULL,
    [CE_STATE_ID]          VARCHAR (255)      NULL,
    [CE_STATE_NAME]        VARCHAR (255)      NULL,
    [CD_CREATED_DATE]      DATETIME           NULL,
    [CD_LAST_MODIFIED]     DATETIME           NULL,
    [CD_JURISDICTION]      VARCHAR (255)      NULL,
    [CD_REFERENCE]         DECIMAL (38)       NULL,
    [LOADED_DATETIME]      DATETIME           NULL,
    [USER_ID]              VARCHAR (100)      NULL,
    [USER_FIRST_NAME]      VARCHAR (100)      NULL,
    [USER_LAST_NAME]       VARCHAR (100)      NULL
)
WITH (CLUSTERED COLUMNSTORE INDEX, DISTRIBUTION = ROUND_ROBIN);

