CREATE TABLE [PROBATE].[TBL_LEGAL_CASE_STATE] (
    [LEGAL_CASE_ID]              DECIMAL (38)    NULL,
    [LEGAL_CASE_TYPE_NAME]       VARCHAR (50)    NULL,
    [LEGAL_CASE_STATE_TYPE_CODE] VARCHAR (50)    NULL,
    [LEGAL_CASE_STATE_EVENT_ID]  DECIMAL (38)    NULL,
    [LEGAL_CASE_STATE_TYPE_NAME] VARCHAR (255)   NULL,
    [STATE_START_TIMESTAMP]      DATETIME2 (6)   NULL,
    [LEGAL_CASE_STATE_END_DATE]  DATETIME2 (6)   NULL,
    [BIS_FIRST_CREATED_DATETIME] DATETIME        NULL,
    [BIS_LAST_MODIFIED_DATETIME] DATETIME        NULL,
    [MODIFIED_BY_PROCESS_NAME]   VARCHAR (50)    NULL,
    [INSERTED_BY_PROCESS_NAME]   VARCHAR (50)    NULL,
    [SOURCE_SYSTEM_TYPE_CODE]    VARCHAR (50)    NULL,
    [LEGAL_CASE_STATE_TYPE_KEY]  DECIMAL (10, 6) NULL,
    [DURTN_DAYS]                 INT             NULL
)
WITH (CLUSTERED COLUMNSTORE INDEX, DISTRIBUTION = ROUND_ROBIN);

