CREATE TABLE [PROBATE].[TBL_LEGAL_CASE] (
    [LEGAL_CASE_ID]                 DECIMAL (38)  NULL,
    [LEGAL_CASE_TYPE_NAME]          VARCHAR (50)  NULL,
    [LEGAL_CASE_TYPE_CODE_VRSN_NBR] FLOAT (53)    NULL,
    [LEGAL_CASE_CREATED_TIMESTAMP]  DATETIME2 (3) NULL,
    [LEGAL_CASE_REFERENCE_ID]       DECIMAL (38)  NULL,
    [JURISDICTION_CODE]             VARCHAR (50)  NULL,
    [LAST_MODIFIED_DATETIME]        DATETIME2 (3) NULL,
    [BIS_FIRST_CREATED_DATETIME]    DATETIME      NULL,
    [BIS_LAST_MODIFIED_DATETIME]    DATETIME      NULL,
    [BIS_MODIFIED_BY_PROCESS_NAME]  VARCHAR (50)  NULL,
    [BIS_INSERTED_BY_PROCESS_NAME]  VARCHAR (50)  NULL,
    [SOURCE_SYSTEM_TYPE_CODE]       VARCHAR (50)  NULL
)
WITH (CLUSTERED COLUMNSTORE INDEX, DISTRIBUTION = ROUND_ROBIN);

