CREATE TABLE [STG].[STG_CCD_METADATA] (
    [MD_INSERT_TIME]       DATETIMEOFFSET (5) NULL,
    [CE_ID]                NUMERIC (38)       NOT NULL,
    [CE_CASE_DATA_ID]      NUMERIC (38)       NULL,
    [CE_CREATED_DATE]      DATETIME2 (3)      NULL,
    [CE_CASE_TYPE_ID]      VARCHAR (255)      NULL,
    [CE_CASE_TYPE_VERSION] NUMERIC (18)       NULL,
    [CE_EVENT_ID]          VARCHAR (100)      NULL,
    [CE_EVENT_NAME]        VARCHAR (255)      NULL,
    [CE_STATE_ID]          VARCHAR (255)      NULL,
    [CE_STATE_NAME]        VARCHAR (255)      NULL,
    [CD_CREATED_DATE]      DATETIME2 (3)      NULL,
    [CD_LAST_MODIFIED]     DATETIME2 (3)      NULL,
    [CD_JURISDICTION]      VARCHAR (255)      NULL,
    [CD_REFERENCE]         NUMERIC (38)       NULL,
    [LOADED_DATETIME]      DATE               NULL,
    [USER_ID]              VARCHAR (100)      NULL,
    [USER_FIRST_NAME]      VARCHAR (100)      NULL,
    [USER_LAST_NAME]       VARCHAR (100)      NULL,
    PRIMARY KEY NONCLUSTERED ([CE_ID] ASC) NOT ENFORCED
)
WITH (CLUSTERED COLUMNSTORE INDEX, DISTRIBUTION = HASH([CE_CASE_DATA_ID]));

