CREATE TABLE [STG].[STG_CCD_TMP_DATA] (
    [MD_INSERT_TIME]       VARCHAR (255)  NULL,
    [CE_ID]                NUMERIC (38)   NOT NULL,
    [CE_CASE_DATA_ID]      NUMERIC (38)   NULL,
    [CE_CREATED_DATE]      NUMERIC (38)   NULL,
    [CE_CASE_TYPE_ID]      VARCHAR (255)  NULL,
    [CE_CASE_TYPE_VERSION] NUMERIC (38)   NULL,
    [CE_EVENT_ID]          VARCHAR (100)  NULL,
    [CE_EVENT_NAME]        VARCHAR (255)  NULL,
    [CE_STATE_ID]          VARCHAR (255)  NULL,
    [CE_STATE_NAME]        VARCHAR (255)  NULL,
    [CD_CREATED_DATE]      VARCHAR (255)  NULL,
    [CD_LAST_MODIFIED]     VARCHAR (255)  NULL,
    [CD_JURISDICTION]      VARCHAR (255)  NULL,
    [CD_REFERENCE]         NUMERIC (38)   NULL,
    [LOADED_DATETIME]      DATE           NULL,
    [USER_ID]              VARCHAR (100)  NULL,
    [USER_FIRST_NAME]      VARCHAR (100)  NULL,
    [USER_LAST_NAME]       VARCHAR (100)  NULL,
    [CE_DATA]              VARCHAR (8000) NULL,
    PRIMARY KEY NONCLUSTERED ([CE_ID] ASC) NOT ENFORCED
)
WITH (CLUSTERED COLUMNSTORE INDEX, DISTRIBUTION = HASH([CE_CASE_DATA_ID]));

